const foodData = {
  "street-food": {
    title: "Gewilde Straatkos",
    meals: [
      {
        id: "kota",
        name: "Kota",
        image: "Images/kota.jpg",
        ingredients: [
          {
            product: "Brood",
            quantity: 10,
            unit: "brode",
            weight: 1,
            price: 10,
          },
          {
            product: "Aartappels",
            quantity: 2,
            unit: "kg",
            weight: 10,
            price: 9.5,
          },
          {
            product: "Russians",
            quantity: 2,
            unit: "kg",
            weight: 5,
            price: 70,
          },
          {
            product: "Eiers",
            quantity: 3,
            unit: "bakkie(s)",
            weight: 1,
            price: 70,
          },
          {
            product: "Atchar",
            quantity: 1,
            unit: "kg",
            weight: 5,
            price: 60,
          },
          {
            product: "Sous: Tamatiesous",
            quantity: 1,
            unit: "l",
            weight: 5,
            price: 65,
          },
          {
            product: "Sous: Soet Chilli",
            quantity: 1,
            unit: "l",
            weight: 5,
            price: 80,
          },
          {
            product: "Sous: Mayonnaise",
            quantity: 1,
            unit: "l",
            weight: 5,
            price: 70,
          },
          {
            product: "Sous: Mosterd",
            quantity: 1,
            unit: "l",
            weight: 2,
            price: 95,
          },
          {
            product: "Sous: Braaisous",
            quantity: 1,
            unit: "l",
            weight: 2,
            price: 55,
          },
          {
            product: "Speserye: Beesvleisspeserye",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 150,
          },
          {
            product: "Speserye: Hoenderspeserye",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 135,
          },
          {
            product: "Speserye: Paprikaspeserye",
            quantity: 1,
            unit: "g",
            weight: 500,
            price: 86.5,
          },
          {
            product: "Speserye: Pepperspeserye",
            quantity: 1,
            unit: "g",
            weight: 500,
            price: 110,
          },
          {
            product: "Speserye: Six Gun",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 130,
          },
          {
            product: "Olie",
            quantity: 4,
            unit: "l",
            weight: 5,
            price: 70,
          },
        ],
      },
      {
        id: "bunny",
        name: "Bunny Chow",
        image: "Images/bunnychow.jpg",
        ingredients: [
          {
            product: "Brood",
            quantity: 10,
            unit: "brode",
            weight: 1,
            price: 10,
          },
          {
            product: "Olie",
            quantity: 4,
            unit: "l",
            weight: 5,
            price: 70,
          },
          {
            product: "Uie",
            quantity: 1,
            unit: "kg",
            weight: 10,
            price: 25,
          },
          {
            product: "Knoffel",
            quantity: 2,
            unit: "kg",
            weight: 1,
            price: 70,
          },
          {
            product: "Borrie",
            quantity: 1,
            unit: "g",
            weight: 500,
            price: 80,
          },
          {
            product: "Chillipoeier",
            quantity: 1,
            unit: "g",
            weight: 500,
            price: 90,
          },
          {
            product: "Tamatie",
            quantity: 5,
            unit: "kg",
            weight: 2,
            price: 30,
          },
          {
            product: "Tamatiepasta",
            quantity: 3,
            unit: "kg",
            weight: 3,
            price: 45,
          },
          {
            product: "Beesvleis",
            quantity: 2,
            unit: "kg",
            weight: 10,
            price: 90,
          },
          {
            product: "Hoender",
            quantity: 3,
            unit: "kg",
            weight: 10,
            price: 80,
          },
          {
            product: "Skaapvleis",
            quantity: 3,
            unit: "kg",
            weight: 5,
            price: 120,
          },
          {
            product: "Aartappels",
            quantity: 2,
            unit: "kg",
            weight: 10,
            price: 9.5,
          },
          {
            product: "Speserye: Beesvleisspeserye",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 150,
          },
          {
            product: "Speserye: Hoenderspeserye",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 135,
          },
          {
            product: "Speserye: Paprikaspeserye",
            quantity: 1,
            unit: "g",
            weight: 500,
            price: 86.5,
          },
          {
            product: "Speserye: Pepperspeserye",
            quantity: 1,
            unit: "g",
            weight: 500,
            price: 110,
          },
          {
            product: "Speserye: Six Gun",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 130,
          },
        ],
      },
      {
        id: "vetkoek",
        name: "Gevulde Vetkoek",
        image: "Images/filledvetkoek.jpg",
        ingredients: [
          {
            product: "Olie",
            quantity: 4,
            unit: "l",
            weight: 5,
            price: 70,
          },
          {
            product: "Meel",
            quantity: 1,
            unit: "kg",
            weight: 25,
            price: 22,
          },
          {
            product: "Suiker",
            quantity: 1,
            unit: "kg",
            weight: 10,
            price: 35,
          },
          {
            product: "Sout",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 25,
          },
          {
            product: "Droë Gis",
            quantity: 1,
            unit: "sakkie(s)",
            weight: 10,
            price: 7,
          },
          {
            product: "Bakpoeier",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 45,
          },
          {
            product: "Rajar (Kerriepoeier)",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 90,
          },
          {
            product: "Rissies",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: "39",
          },
          {
            product: "Maalvleis",
            quantity: 5,
            unit: "kg",
            weight: 3,
            price: 100,
          },
          {
            product: "Sop",
            quantity: 20,
            unit: "pakkie(s)",
            weight: 1,
            price: "15",
          },
          {
            product: "Kaas",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 110,
          },
          {
            product: "Konfyt",
            quantity: 3,
            unit: "kg",
            weight: 1,
            price: 55,
          },
          {
            product: "Sous: Tamatiesous",
            quantity: 1,
            unit: "l",
            weight: 5,
            price: 65,
          },
          {
            product: "Sous: Soet Chilli",
            quantity: 1,
            unit: "l",
            weight: 5,
            price: 80,
          },
          {
            product: "Sous: Mayonnaise",
            quantity: 1,
            unit: "l",
            weight: 5,
            price: 70,
          },
          {
            product: "Sous: Mosterd",
            quantity: 1,
            unit: "l",
            weight: 2,
            price: 95,
          },
          {
            product: "Sous: Braaisous",
            quantity: 1,
            unit: "l",
            weight: 2,
            price: 55,
          },
          {
            product: "Speserye: Beesvleisspeserye",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 150,
          },
          {
            product: "Speserye: Hoenderspeserye",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 135,
          },
          {
            product: "Speserye: Paprikaspeserye",
            quantity: 1,
            unit: "g",
            weight: 500,
            price: 86.5,
          },
          {
            product: "Speserye: Pepperspeserye",
            quantity: 1,
            unit: "g",
            weight: 500,
            price: 110,
          },
          {
            product: "Speserye: Six Gun",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 130,
          },
        ],
      },
      {
        id: "boerewors",
        name: "Boereworsrolletjie",
        image: "Images/worsroll.jpg",
        ingredients: [
          {
            product: "Worsbroodjies",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 15,
          },
          {
            product: "Boerewors",
            quantity: 4,
            unit: "kg",
            weight: 5,
            price: 110,
          },
          {
            product: "Olie",
            quantity: 4,
            unit: "l",
            weight: 5,
            price: 70,
          },
          {
            product: "Sous: Tamatiesous",
            quantity: 1,
            unit: "l",
            weight: 5,
            price: 65,
          },
          {
            product: "Sous: Soet Chilli",
            quantity: 1,
            unit: "l",
            weight: 5,
            price: 80,
          },
          {
            product: "Sous: Mayonnaise",
            quantity: 1,
            unit: "l",
            weight: 5,
            price: 70,
          },
          {
            product: "Sous: Mosterd",
            quantity: 1,
            unit: "l",
            weight: 2,
            price: 95,
          },
        ],
      },
      {
        id: "russian",
        name: "Russian met Skyfies",
        image: "Images/russianchips.jpg",
        ingredients: [
          {
            product: "Aartappels",
            quantity: 2,
            unit: "kg",
            weight: 10,
            price: 9.5,
          },
          {
            product: "Russians",
            quantity: 2,
            unit: "kg",
            weight: 5,
            price: 70,
          },
          {
            product: "Olie",
            quantity: 4,
            unit: "l",
            weight: 5,
            price: 70,
          },
          {
            product: "Sous: Tamatiesous",
            quantity: 1,
            unit: "l",
            weight: 5,
            price: 65,
          },
          {
            product: "Sous: Soet Chilli",
            quantity: 1,
            unit: "l",
            weight: 5,
            price: 80,
          },
          {
            product: "Sous: Mayonnaise",
            quantity: 1,
            unit: "l",
            weight: 5,
            price: 70,
          },
          {
            product: "Sous: Mosterd",
            quantity: 1,
            unit: "l",
            weight: 2,
            price: 95,
          },
          {
            product: "Sous: Braaisous",
            quantity: 1,
            unit: "l",
            weight: 2,
            price: 55,
          },
          {
            product: "Speserye: Beesvleisspeserye",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 150,
          },
          {
            product: "Speserye: Hoenderspeserye",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 135,
          },
          {
            product: "Speserye: Paprikaspeserye",
            quantity: 1,
            unit: "g",
            weight: 500,
            price: 86.5,
          },
          {
            product: "Speserye: Pepperspeserye",
            quantity: 1,
            unit: "g",
            weight: 500,
            price: 110,
          },
          {
            product: "Speserye: Six Gun",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 130,
          },
        ],
      },
    ],
  },
  traditional: {
    title: "Tradisionele Etes",
    meals: [
      {
        id: "papwors",
        name: "Pap & Wors",
        image: "Images/papwors.jpg",
        ingredients: [
          {
            product: "Sout",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 25,
          },
          {
            product: "Mieliemeel",
            quantity: 1,
            unit: "kg",
            weight: 25,
            price: 25,
          },
          {
            product: "Uie",
            quantity: 1,
            unit: "kg",
            weight: 10,
            price: 25,
          },
          {
            product: "Boerewors",
            quantity: 4,
            unit: "kg",
            weight: 5,
            price: 110,
          },
          {
            product: "Olie",
            quantity: 4,
            unit: "kg",
            weight: 5,
            price: 70,
          },
        ],
      },
      {
        id: "papstew",
        name: "Pap & Bredie",
        image: "Images/papstew.jpg",
        ingredients: [
          {
            product: "Sout",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 25,
          },
          {
            product: "Mieliemeel",
            quantity: 1,
            unit: "kg",
            weight: 25,
            price: 25,
          },
          {
            product: "Beesvleis",
            quantity: 2,
            unit: "kg",
            weight: 10,
            price: 90,
          },
          {
            product: "Hoender",
            quantity: 3,
            unit: "kg",
            weight: 10,
            price: 80,
          },
          {
            product: "Osstert",
            quantity: 5,
            unit: "kg",
            weight: 2,
            price: 180,
          },
          {
            product: "Rajar (Kerriepoeier)",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 90,
          },
          {
            product: "Uie",
            quantity: 1,
            unit: "kg",
            weight: 10,
            price: 25,
          },
          {
            product: "Rissies",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 39,
          },
          {
            product: "Sop",
            quantity: 20,
            unit: "pakkie(s)",
            weight: 1,
            price: 15,
          },
          {
            product: "Olie",
            quantity: 4,
            unit: "l",
            weight: 5,
            price: 70,
          },
          {
            product: "Beesvleisaftreksel",
            quantity: 2,
            unit: "kg",
            weight: 1,
            price: 60,
          },
          {
            product: "Aartappels",
            quantity: 2,
            unit: "kg",
            weight: 10,
            price: 9.5,
          },
          {
            product: "Speserye: Beesvleisspeserye",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 150,
          },
          {
            product: "Speserye: Hoenderspeserye",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 135,
          },
          {
            product: "Speserye: Paprikaspeserye",
            quantity: 1,
            unit: "g",
            weight: 500,
            price: 86.5,
          },
          {
            product: "Speserye: Pepperspeserye",
            quantity: 1,
            unit: "g",
            weight: 500,
            price: 110,
          },
          {
            product: "Speserye: Six Gun",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 130,
          },
        ],
      },
      {
        id: "chickenfeet",
        name: "Amanqina met Pap",
        image: "Images/amanqina.jpg",
        ingredients: [
          {
            product: "Hoenderpootjies",
            quantity: 5,
            unit: "kg",
            weight: 2,
            price: 30,
          },
          {
            product: "Rajar (Kerriepoeier)",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 90,
          },
          {
            product: "Rissies",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 39,
          },
          {
            product: "Sop",
            quantity: 20,
            unit: "kg",
            weight: 1,
            price: 22,
          },
          {
            product: "Olie",
            quantity: 4,
            unit: "l",
            weight: 5,
            price: 70,
          },
          {
            product: "Beesvleisaftreksel",
            quantity: 2,
            unit: "kg",
            weight: 1,
            price: 60,
          },
          {
            product: "Aartappels",
            quantity: 2,
            unit: "kg",
            weight: 10,
            price: 9.5,
          },
          {
            product: "Uie",
            quantity: 1,
            unit: "kg",
            weight: 10,
            price: 25,
          },
          {
            product: "Sout",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 25,
          },
          {
            product: "Mieliemeel",
            quantity: 1,
            unit: "kg",
            weight: 25,
            price: 25,
          },
          {
            product: "Speserye: Beesvleisspeserye",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 150,
          },
          {
            product: "Speserye: Hoenderspeserye",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 135,
          },
          {
            product: "Speserye: Paprikaspeserye",
            quantity: 1,
            unit: "g",
            weight: 500,
            price: 86.5,
          },
          {
            product: "Speserye: Pepperspeserye",
            quantity: 1,
            unit: "g",
            weight: 500,
            price: 110,
          },
          {
            product: "Speserye: Six Gun",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 130,
          },
        ],
      },
      {
        id: "papmogodu",
        name: "Mogodu met Pap",
        image: "Images/papmogodu.jpg",
        ingredients: [
          {
            product: "Pens",
            quantity: 3,
            unit: "kg",
            weight: 5,
            price: 55,
          },
          {
            product: "Rajar (Kerriepoeier)",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 90,
          },
          {
            product: "Rissies",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 39,
          },
          {
            product: "Sop",
            quantity: 20,
            unit: "kg",
            weight: 1,
            price: 15,
          },
          {
            product: "Olie",
            quantity: 4,
            unit: "l",
            weight: 5,
            price: 70,
          },
          {
            product: "Uie",
            quantity: 1,
            unit: "kg",
            weight: 10,
            price: 25,
          },
          {
            product: "Beesvleisaftreksel",
            quantity: 2,
            unit: "kg",
            weight: 1,
            price: 60,
          },
          {
            product: "Aartappels",
            quantity: 2,
            unit: "kg",
            weight: 10,
            price: 9.5,
          },
          {
            product: "Sout",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 25,
          },
          {
            product: "Mieliemeel",
            quantity: 1,
            unit: "kg",
            weight: 25,
            price: 25,
          },
          {
            product: "Speserye: Beesvleisspeserye",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 150,
          },
          {
            product: "Speserye: Hoenderspeserye",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 135,
          },
          {
            product: "Speserye: Paprikaspeserye",
            quantity: 1,
            unit: "g",
            weight: 500,
            price: 86.5,
          },
          {
            product: "Speserye: Pepperspeserye",
            quantity: 1,
            unit: "g",
            weight: 500,
            price: 110,
          },
          {
            product: "Speserye: Six Gun",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 130,
          },
        ],
      },
      {
        id: "chickenliver",
        name: "Hoenderlewer met Pap",
        image: "Images/chickenliver.jpg",
        ingredients: [
          {
            product: "Hoenderlewer",
            quantity: 20,
            unit: "kg",
            weight: 500,
            price: 45,
          },
          {
            product: "Rajar (Kerriepoeier)",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 90,
          },
          {
            product: "Rissies",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 39,
          },
          {
            product: "Sop",
            quantity: 20,
            unit: "kg",
            weight: 1,
            price: 15,
          },
          {
            product: "Olie",
            quantity: 4,
            unit: "l",
            weight: 5,
            price: 70,
          },
          {
            product: "Uie",
            quantity: 1,
            unit: "kg",
            weight: 10,
            price: 25,
          },
          {
            product: "Beesvleisaftreksel",
            quantity: 2,
            unit: "kg",
            weight: 1,
            price: 60,
          },
          {
            product: "Aartappels",
            quantity: 2,
            unit: "kg",
            weight: 10,
            price: 9.5,
          },
          {
            product: "Sout",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 25,
          },
          {
            product: "Mieliemeel",
            quantity: 1,
            unit: "kg",
            weight: 25,
            price: 25,
          },
          {
            product: "Speserye: Beesvleisspeserye",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 150,
          },
          {
            product: "Speserye: Hoenderspeserye",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 135,
          },
          {
            product: "Speserye: Paprikaspeserye",
            quantity: 1,
            unit: "g",
            weight: 500,
            price: 86.5,
          },
          {
            product: "Speserye: Pepperspeserye",
            quantity: 1,
            unit: "g",
            weight: 500,
            price: 110,
          },
          {
            product: "Speserye: Six Gun",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 130,
          },
        ],
      },
    ],
  },
  "light-meals": {
    title: "Ligte Etes",
    meals: [
      {
        id: "amagwinya",
        name: "Amagwinya",
        image: "Images/amagwinya.jpeg",
        ingredients: [
          {
            product: "Olie",
            quantity: 4,
            unit: "l",
            weight: 5,
            price: 70,
          },
          {
            product: "Meel",
            quantity: 1,
            unit: "kg",
            weight: 25,
            price: 22,
          },
          {
            product: "Suiker",
            quantity: 1,
            unit: "kg",
            weight: 10,
            price: 35,
          },
          {
            product: "Sout",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 25,
          },
          {
            product: "Droë Gis",
            quantity: 1,
            unit: "sakkie(s)",
            weight: 10,
            price: 7,
          },
          {
            product: "Bakpoeier",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 45,
          },
        ],
      },
      {
        id: "chips",
        name: "Slapskyfies",
        image: "Images/slapchips.jpg",
        ingredients: [
          {
            product: "Olie",
            quantity: 4,
            unit: "l",
            weight: 5,
            price: 70,
          },
          {
            product: "Aartappels",
            quantity: 2,
            unit: "kg",
            weight: 10,
            price: 9.5,
          },
          {
            product: "Asyn",
            quantity: 2,
            unit: "l",
            weight: 2,
            price: 25,
          },
          {
            product: "Sous: Tamatiesous",
            quantity: 1,
            unit: "l",
            weight: 5,
            price: 65,
          },
          {
            product: "Sous: Soet Chilli",
            quantity: 1,
            unit: "l",
            weight: 5,
            price: 80,
          },
          {
            product: "Sous: Mayonnaise",
            quantity: 1,
            unit: "l",
            weight: 5,
            price: 70,
          },
          {
            product: "Sous: Mosterd",
            quantity: 1,
            unit: "l",
            weight: 2,
            price: 95,
          },
          {
            product: "Sous: Braaisous",
            quantity: 1,
            unit: "l",
            weight: 2,
            price: 55,
          },
          {
            product: "Speserye: Beesvleisspeserye",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 150,
          },
          {
            product: "Speserye: Hoenderspeserye",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 135,
          },
          {
            product: "Speserye: Paprikaspeserye",
            quantity: 1,
            unit: "g",
            weight: 500,
            price: 86.5,
          },
          {
            product: "Speserye: Pepperspeserye",
            quantity: 1,
            unit: "g",
            weight: 500,
            price: 110,
          },
          {
            product: "Speserye: Six Gun",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 130,
          },
        ],
      },
      {
        id: "sandwich",
        name: "Roosterbroodjie",
        image: "Images/cheeseandham.jpg",
        ingredients: [
          {
            product: "Brood",
            quantity: 10,
            unit: "brode",
            weight: 1,
            price: 20,
          },
          {
            product: "Eiers",
            quantity: 3,
            unit: "bakkie(s)",
            weight: 1,
            price: 70,
          },
          {
            product: "Kaas",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 110,
          },
          {
            product: "Ham",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 110,
          },
          {
            product: "Polonie",
            quantity: 10,
            unit: "kg",
            weight: 1,
            price: 50,
          },
          {
            product: "Tamatie",
            quantity: 5,
            unit: "kg",
            weight: 2,
            price: 30,
          },
        ],
      },
      {
        id: "smiley",
        name: "Intloko",
        image: "Images/smiley.jpg",
        ingredients: [
          {
            product: "Bokkop",
            quantity: 10,
            unit: "kop(pe)",
            weight: 1,
            price: 150,
          },
          {
            product: "Bokpootjies",
            quantity: 10,
            unit: "kg",
            weight: 1,
            price: 60,
          },
          {
            product: "Skaapkop",
            quantity: 10,
            unit: "kop(pe)",
            weight: 1,
            price: 130,
          },
          {
            product: "Skaappootjies",
            quantity: 10,
            unit: "kg",
            weight: 1,
            price: 55,
          },
        ],
      },
    ],
  },
  "baked-goods": {
    title: "Gebak",
    meals: [
      {
        id: "scones",
        name: "Skons",
        image: "Images/scones.jpg",
        ingredients: [
          {
            product: "Meel",
            quantity: 1,
            unit: "kg",
            weight: 25,
            price: 22,
          },
          {
            product: "Suiker",
            quantity: 1,
            unit: "kg",
            weight: 10,
            price: 35,
          },
          {
            product: "Sout",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 25,
          },
          {
            product: "Bakpoeier",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 45,
          },
          {
            product: "Melk",
            quantity: 20,
            unit: "l",
            weight: 1,
            price: 17,
          },
          {
            product: "Botter",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 140,
          },
          {
            product: "Konfyt",
            quantity: 3,
            unit: "kg",
            weight: 1,
            price: 55,
          },
        ],
      },
      {
        id: "muffins",
        name: "Muffins",
        image: "Images/muffins.jpg",
        ingredients: [
          {
            product: "Alledoelige Meel",
            quantity: 1,
            unit: "kg",
            weight: 10,
            price: 21,
          },
          {
            product: "Suiker",
            quantity: 1,
            unit: "kg",
            weight: 10,
            price: 35,
          },
          {
            product: "Sout",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 25,
          },
          {
            product: "Bakpoeier",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 45,
          },
          {
            product: "Melk",
            quantity: 20,
            unit: "l",
            weight: 1,
            price: 17,
          },
          {
            product: "Botter",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 140,
          },
          {
            product: "Olie",
            quantity: 4,
            unit: "l",
            weight: 5,
            price: 70,
          },
          {
            product: "Vanielje",
            quantity: 2,
            unit: "ml",
            weight: 500,
            price: 140,
          },
        ],
      },
      {
        id: "koeksisters",
        name: "Koeksisters",
        image: "Images/koeksisters.jpg",
        ingredients: [
          {
            product: "Meel",
            quantity: 1,
            unit: "kg",
            weight: 25,
            price: 22,
          },
          {
            product: "Suiker",
            quantity: 1,
            unit: "kg",
            weight: 10,
            price: 35,
          },
          {
            product: "Sout",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 25,
          },
          {
            product: "Bakpoeier",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 45,
          },
          {
            product: "Melk",
            quantity: 20,
            unit: "l",
            weight: 1,
            price: 17,
          },
          {
            product: "Eiers",
            quantity: 3,
            unit: "bakkie(s)",
            weight: 1,
            price: 70,
          },
          {
            product: "Botter",
            quantity: 5,
            unit: "kg",
            weight: 1,
            price: 140,
          },
          {
            product: "Olie",
            quantity: 4,
            unit: "l",
            weight: 5,
            price: 70,
          },
        ],
      },
    ],
  },
  drinks: {
    title: "Drankies",
    meals: [
      {
        id: "ginger",
        name: "Tuisgemaakte Gemmerbier",
        image: "Images/gingerbeer.jpg",
        ingredients: [
          {
            product: "Suiker",
            quantity: 1,
            unit: "kg",
            weight: 10,
            price: 35,
          },
          {
            product: "Droë Gis",
            quantity: 1,
            unit: "sakkie(s)",
            weight: 10,
            price: 7,
          },
          {
            product: "Organiese Gemmerpoeier",
            quantity: 10,
            unit: "kg",
            weight: 1,
            price: 90,
          },
        ],
      },
      {
        id: "softdrinks",
        name: "Koeldrank",
        image: "Images/softdrinks.jpg",
        ingredients: [
          {
            product: "Koeldrank",
            quantity: 5,
            unit: "kas",
            weight: 1,
            price: 210,
          },
        ],
      },
      {
        id: "water",
        name: "Gebottelde Water",
        image: "Images/bottledwater.jpg",
        ingredients: [
          {
            product: "Gebottelde Water",
            quantity: 5,
            unit: "kas",
            weight: 1,
            price: 170,
          },
        ],
      },
      {
        id: "juice",
        name: "Sap",
        image: "Images/juice.jpg",
        ingredients: [
          {
            product: "Sap",
            quantity: 4,
            unit: "l",
            weight: 5,
            price: 30,
          },
        ],
      },
      {
        id: "tea",
        name: "Tee",
        image: "Images/tea.png",
        ingredients: [
          {
            product: "Teesakkie",
            quantity: 5,
            unit: "boks (100s)",
            weight: 1,
            price: 45,
          },
          {
            product: "Melk",
            quantity: 20,
            unit: "l",
            weight: 1,
            price: 17,
          },
          {
            product: "Suiker",
            quantity: 1,
            unit: "kg",
            weight: 10,
            price: 35,
          },
        ],
      },
      {
        id: "coffee",
        name: "Koffie",
        image: "Images/coffee.jpg",
        ingredients: [
          {
            product: "Koffie",
            quantity: 2,
            unit: "kg",
            weight: 1,
            price: 350,
          },
          {
            product: "Melkpoeier",
            quantity: 2,
            unit: "kg",
            weight: 1,
            price: 100,
          },
          {
            product: "Melk",
            quantity: 20,
            unit: "l",
            weight: 1,
            price: 17,
          },
          {
            product: "Suiker",
            quantity: 1,
            unit: "kg",
            weight: 1,
            price: 35,
          },
        ],
      },
    ],
  },
};
